### ISSUE TITLE
chimney sweep

### ISSUE THREAD

**Issue by richardwan** [wanfamilia/todo#4]
cleaning and inspection

**Comment by richardwan** [comment]
- [ ] find 3 chimney sweepers, send to deanna
- [ ] deanna review with bureau
- [ ] ask ballpark phone estimates to clean and and inspect wood/gas chimney and fireplace
- [ ] joint discussion
- [ ] schedule work
- [ ] oversee work

**Comment by richardwan** [comment]
- [ ] http://calgarychimneysweeps.org/
- [ ] http://www.ablesweeps.com/
- [ ] http://oldelondonchimneysweep.com/

**Comment by deannawan** [comment]
You can call: Able Sweeps
and:
http://www.albertachimneysweep.com/

**Comment by deannawan** [comment]
schedule either

**Comment by deannawan** [comment]
schedule either
